### ISSUE TITLE
请教下如何解密slave和jobs配置文件~

### ISSUE THREAD

**Issue by G4rb3n** [0xjiayu/DDGBotnetTracker#1]
问下，项目中的slave.raw和jobs.raw，是怎么解密成slave.json和jobs.json的~

**Comment by 0xjiayu** [comment]
slave.raw 的解码，核心就是这个数据结构。拿到这个数据结构，用 msgpack 解出来即可，v1 版的源码里有详细过程：
https://github.com/0xjiayu/DDGBotnetTracker/blob/master/v1/lib/slave_conf.go

另外一个简便的方式，是你去用 Python + msgpack 去解，不需要事先知道数据结构也能解出来。

jobs.raw 的解密源码我没公开，不过解密原理在分析报告里都写了，感兴趣可以自己写代码解密一下。
分析报告： [DDG的新征程——自研P2P协议构建混合P2P网络](https://blog.netlab.360.com/ddg-upgrade-to-new-p2p-hybrid-model/)

**Comment by G4rb3n** [comment]
好的，谢谢~我试试

**Comment by 0xjiayu** [comment]
> 好的，谢谢~我试试

我前两天刚开源了自用的一个解析 Go 二进制文件的 IDAPro 插件，会更方便这种复杂结构体的逆向分析，不妨试试看 :-)

https://github.com/0xjiayu/go_parser
